baseurl = "/"
title = "Rafa Alkalai"
author = "Rafa Alkalai"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

publishDir = "docs/"
# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "Rafa Alkalai"
faviconfile = "image/favicon.png"
logofile = "image/avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "ralkalai"
twitter = "ralkalai"
email = "ralkalai@student.ubc.ca"

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "books"
name = "Bookshelf"
url = "/books/"
weight = 2

[[menu.primary]]
identifier = "music"
name = "Music"
url = "/music/"
weight = 3
